# Generated by Django 5.0.6 on 2024-09-10 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(upload_to='partners/')),
                ('website', models.URLField()),
            ],
        ),
    ]
