# Generated by Django 5.0.6 on 2024-09-10 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='certificate',
            field=models.TextField(default='test sertificate'),
            preserve_default=False,
        ),
    ]
