version: '3.1'

services:
  db:
    container_name: db
    image: mariadb:10.11
    environment:
      MYSQL_ROOT_PASSWORD: notSecureChangeMe
      MYSQL_USER: marat
      MYSQL_PASSWORD: 1234
    networks:
      - mynetwork
    volumes:
      - db_data:/var/lib/mysql

  
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80  
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
    networks:
      - mynetwork
    depends_on:
      - db

networks:
  mynetwork:

volumes:
  db_data: