# Generated by Django 5.0.4 on 2024-05-17 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата заказа')),
                ('completion_date', models.DateField(verbose_name='Дата выполнения заказа')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('promocode', models.CharField(blank=True, max_length=20, verbose_name='Промокод')),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Выручка')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='PickupPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование точки самовывоза')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Точка самовывоза',
                'verbose_name_plural': 'Точки самовывоза',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('code', models.IntegerField(verbose_name='Код продукта')),
                ('model', models.CharField(max_length=50, verbose_name='Модель')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('production_time', models.IntegerField(verbose_name='Время изготовления')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Картинка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Вид изделия')),
            ],
            options={
                'verbose_name': 'Тип мебели',
                'verbose_name_plural': 'Типы мебели',
            },
        ),
        migrations.CreateModel(
            name='Promocode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название промокода')),
                ('description', models.TextField(verbose_name='Описание промокода')),
                ('code', models.CharField(max_length=255, verbose_name='Код промокода')),
                ('discount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Скидка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
            },
        ),
    ]
